name: Build and Package React Component Library

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Fetch all tags
        run: git fetch --tags

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Version Package
        run: npm version ${{ steps.find_tag.outputs.tag_name }}

      - name: Build the project
        run: npm run rollup

      - name: Package the build artifacts
        run: npm pack

      - name: Get release by tag
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const tag = '${{ steps.find_tag.outputs.tag_name }}';
            const release = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tag
            });
            core.setOutput('release_id', release.data.id);
            core.setOutput('upload_url', release.data.upload_url);

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./liatrio-react-dora-${{ steps.find_tag.outputs.tag_name }}.tgz
          asset_name: liatrio-react-dora-${{ steps.find_tag.outputs.tag_name }}.tgz
          asset_content_type: application/gzip
