export default `{
    "records": [
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "c35fbad39cbdce739e2b5bf9fa9fa666b8cd566b",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-08-07T08:59:33Z",
            "created_at": "2024-08-07T09:59:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "255f312c481cdf0777172c34470299d3ffbc449f",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-29T10:32:33Z",
            "created_at": "2024-07-29T11:32:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "0c3ada5c873222cab968680916b4d408fa1ed48a",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-16T08:29:33Z",
            "created_at": "2024-07-16T09:29:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "143bf3cb91fc9cd29f478d1e58c8c4a2f02eb45b",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-23T08:54:33Z",
            "created_at": "2024-07-23T09:54:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "a71dba81e7cff17e078a4c9a7ce5ab4e8303e515",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-24T08:30:33Z",
            "created_at": "2024-07-24T09:30:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "27935426198aa0f1b0acdbb216d60b42a953a84b",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-26T08:31:33Z",
            "created_at": "2024-07-26T09:31:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "95bada3455b1490ac9184b571aebf389e75ccfb0",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-12T08:16:33Z",
            "created_at": "2024-07-12T09:16:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "8c7be665702601c9849ac6be44aa80e9acef1c17",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-16T13:25:33Z",
            "created_at": "2024-07-16T14:25:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "485d6ee4a06baf2ac9b5ab517948486abfa76cd2",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-13T08:54:33Z",
            "created_at": "2024-07-13T09:54:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "52ed0390044af34c7186ea24e9606abc79f8c698",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-08-01T08:25:33Z",
            "created_at": "2024-08-01T09:25:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "7161406fdfa44313c33df1f52b543143005332a5",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-08-03T08:29:33Z",
            "created_at": "2024-08-03T09:29:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "215db95d110083658ccae65e34ca0e6aa20662d6",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-08-05T12:00:33Z",
            "created_at": "2024-08-05T13:00:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "8b48397d0eca48534463518ecb57d32d60ba6f3d",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-08-02T13:40:33Z",
            "created_at": "2024-08-02T14:40:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "525ab5c90a9c1a36f6ba55954f8baf656d4e4dcb",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-08-09T08:47:33Z",
            "created_at": "2024-08-09T09:47:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "e0e4f91c04ebb7c4c3bdcfec57e0bfd91f9993ad",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-31T08:40:33Z",
            "created_at": "2024-07-31T09:40:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "be2627cc232afe4c0f937543e7391bee6717087d",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-17T08:33:33Z",
            "created_at": "2024-07-17T09:33:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "ea10ff6e4fadd16314acfa27a4a1403a76286422",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-27T08:29:33Z",
            "created_at": "2024-07-27T09:29:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "e94844be08f356449037802cd8f867dbb3b31ec2",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-08-02T08:23:33Z",
            "created_at": "2024-08-02T09:23:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "f9a042853fcb7090981c2c8433711b69520b7659",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-08-10T08:54:33Z",
            "created_at": "2024-08-10T09:54:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "d158f53aa3ad9fc258bb9371ae2b5a0357ae0ec3",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-08-07T15:24:33Z",
            "created_at": "2024-08-07T16:24:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "486ac6f31e6f74b64d992391b9c5d5cd10c4b479",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-18T08:05:33Z",
            "created_at": "2024-07-18T09:05:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "47223fcb471128fc9c3e3c2ca9176ed984d480de",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-16T12:12:33Z",
            "created_at": "2024-07-16T13:12:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "07c0638267f3e471faf836d2d6fa614c65061390",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-08-06T08:19:33Z",
            "created_at": "2024-08-06T09:19:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "351d2d519d47b074a4bfba2670e5ef22acce0b5f",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-15T11:45:33Z",
            "created_at": "2024-07-15T12:45:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "f2eb035f6451b6c9ea456d6abbae2cc10040d36c",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-30T08:41:33Z",
            "created_at": "2024-07-30T09:41:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "ade6126a5320b6bec6140ea7bf28dabdbacab9a3",
            "status": true,
            "failed_at": "2024-07-22T17:36:33Z",
            "merged_at": "2024-07-22T16:36:33Z",
            "created_at": "2024-07-22T17:36:33Z",
            "fixed_at": "2024-07-22T17:36:33Z",
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": "",
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "26ed9b325365785be5ef06c2f43d87b3a816f3db",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-29T12:53:33Z",
            "created_at": "2024-07-29T13:53:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "c2b1fc7e4b48106278c9bdf5731c00656d995ee6",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-08-08T08:15:33Z",
            "created_at": "2024-08-08T09:15:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "b91bee5071489552740369bf9bb70f59f959a392",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-08-01T09:31:33Z",
            "created_at": "2024-08-01T10:31:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "e0fc6249544a0743f14f77a91ea5f5872bc70a75",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-25T08:16:33Z",
            "created_at": "2024-07-25T09:16:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "26458bff893594e497f6b4a2f3c9bccd8a5040b0",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-19T08:15:33Z",
            "created_at": "2024-07-19T09:15:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "8bef8e8cf5edff5c065294de37cc9e467b843e73",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-20T08:13:33Z",
            "created_at": "2024-07-20T09:13:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "d207ca12b41e2992ae7d0c25ce82c24dffdd9574",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-08-08T12:18:33Z",
            "created_at": "2024-08-08T13:18:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        },
        {
            "repository": "dora-elite-repo",
            "team": "dora-elite-repo",
            "title": "feat: set version v0.3.0",
            "user": "adrielp",
            "sha": "0bee2a81fc903ab9492e65066b7ae6f2d9a518e9",
            "status": true,
            "failed_at": null,
            "merged_at": "2024-07-25T15:00:33Z",
            "created_at": "2024-07-25T16:00:33Z",
            "fixed_at": null,
            "fixed_url": null,
            "deploy_url": "",
            "issue_url": null,
            "change_url": "https://github.com/liatrio/dora-deploy-demo/commit/"
        }
    ]
}`